#pragma once

#include <pebble.h>

// AppMessage keys: use the MESSAGE_KEY_* macros generated by the SDK from
// package.json "messageKeys" (build/src/include/appinfo.h, included via
// pebble.h). Do NOT hand-define key values here.

// Open AppMessage buffers and register handlers.
// Must be called after watchface_create() (panels exist) so incoming
// messages can be dispatched immediately.
void appmessage_init(void);

