#pragma once

#include <pebble.h>

// AppMessage keys: use the MESSAGE_KEY_* macros generated by the SDK from
// package.json "messageKeys" (build/src/include/appinfo.h, included via
// pebble.h). Do NOT hand-define key values here.

// Open AppMessage buffers and register handlers.
// Must be called after watchface_create() (panels exist) so incoming
// messages can be dispatched immediately.
void appmessage_init(void);

// Ask the phone to refresh weather data (sent on watch tick every 30 min).
// The PKJS side listens for this key on its 'appmessage' event.
void appmessage_request_weather(void);

